gl_function(void, glActiveTexture, (GLenum))
gl_function(void, glAttachShader, (GLuint, GLuint))
gl_function(void, glDetachShader, (GLuint, GLuint))
gl_function(void, glBindAttribLocation, (GLuint, GLuint, const char *))
gl_function(void, glBindTexture, (GLenum, GLuint))
gl_function(void, glBlendFuncSeparate, (GLenum, GLenum, GLenum, GLenum))
gl_function(void, glClear, (GLbitfield))
gl_function(void, glClearColor, (GLclampf, GLclampf, GLclampf, GLclampf))
gl_function(void, glCompileShader, (GLuint))
gl_function(GLuint, glCreateProgram, (void))
gl_function(GLuint, glCreateShader, (GLenum))
gl_function(void, glDeleteBuffers, (GLsizei, const GLuint *))
gl_function(void, glDeleteProgram, (GLuint))
gl_function(void, glDeleteShader, (GLuint))
gl_function(void, glDeleteTextures, (GLsizei, const GLuint *))
gl_function(void, glDisable, (GLenum))
gl_function(void, glDisableVertexAttribArray, (GLuint))
gl_function(void, glDrawArrays, (GLenum, GLint, GLsizei))
gl_function(void, glEnable, (GLenum))
gl_function(void, glBlendFunc, (GLenum, GLenum))
gl_function(void, glBlendEquation, (GLenum))
gl_function(void, glDrawElements, (GLenum, GLsizei, GLenum, const GLvoid *))
gl_function(void, glEnableVertexAttribArray, (GLuint))
gl_function(void, glFinish, (void))
gl_function(void, glGenFramebuffers, (GLsizei, GLuint *))
gl_function(void, glGenTextures, (GLsizei, GLuint *))
gl_function(void, glGetBooleanv, (GLenum, GLboolean *))
gl_function(const GLubyte *, glGetString, (GLenum))
gl_function(GLenum, glGetError, (void))
gl_function(void, glGetIntegerv, (GLenum, GLint *))
gl_function(void, glGetProgramiv, (GLuint, GLenum, GLint *))
gl_function(void, glGetShaderInfoLog, (GLuint, GLsizei, GLsizei *, char *))
gl_function(void, glGetShaderiv, (GLuint, GLenum, GLint *))
gl_function(GLint, glGetUniformLocation, (GLuint, const char *))
gl_function(void, glLinkProgram, (GLuint))
gl_function(void, glPixelStorei, (GLenum, GLint))
gl_function(void, glReadPixels, (GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid*))
gl_function(void, glScissor, (GLint, GLint, GLsizei, GLsizei))
gl_function(void, glShaderBinary, (GLsizei, const GLuint *, GLenum, const void *, GLsizei))
gl_function(void, glShaderSource, (GLuint, GLsizei, const GLchar**, const GLint *))
gl_function(void, glTexImage2D, (GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const void *))
gl_function(void, glTexParameteri, (GLenum, GLenum, GLint))
gl_function(void, glTexSubImage2D, (GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))
gl_function(void, glUniform1i, (GLint, GLint))
gl_function(void, glUniform4f, (GLint, GLfloat, GLfloat, GLfloat, GLfloat))
gl_function(void, glUniformMatrix4fv, (GLint, GLsizei, GLboolean, const GLfloat *))
gl_function(void, glUseProgram, (GLuint))
gl_function(void, glVertexAttribPointer, (GLuint, GLint, GLenum, GLboolean, GLsizei, const void *))
gl_function(void, glViewport, (GLint, GLint, GLsizei, GLsizei))
gl_function(void, glBindFramebuffer, (GLenum, GLuint))
gl_function(void, glFramebufferTexture2D, (GLenum, GLenum, GLenum, GLuint, GLint))
gl_function(GLenum, glCheckFramebufferStatus, (GLenum))
gl_function(void, glDeleteFramebuffers, (GLsizei, const GLuint *))
gl_function(GLint, glGetAttribLocation, (GLuint, const GLchar *))
gl_function(void, glGetProgramInfoLog, (GLuint, GLsizei, GLsizei*, GLchar*))
gl_function(void, glGenBuffers, (GLsizei, GLuint *))
gl_function(void, glBindBuffer, (GLenum, GLuint))
gl_function(void, glBufferData, (GLenum, GLsizeiptr, const GLvoid *, GLenum))
gl_function(void, glBufferSubData, (GLenum, GLintptr, GLsizeiptr, const GLvoid *))
